name: Verify and sync

on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            apk --no-cache add msttcorefonts-installer fontconfig && update-ms-fonts && fc-cache -f
            make all

      - name: Publish PDF as actions assets
        uses: actions/upload-artifact@v2
        with:
          name: Example-PDF
          path: main-example.pdf
